#!/usr/bin/env node

process.env.GLOBAL_AGENT_ENVIRONMENT_VARIABLE_NAMESPACE = '';

import 'global-agent/bootstrap';
import yargs, { Argv } from 'yargs';

import * as analyzeCommand from './commands/analyze';
import * as testConnectionCommand from './commands/test-connection';
import { apiMiddleware } from './middlewares/api.middleware';
import { loggerMiddleware } from './middlewares/logger.middleware';

(yargs as Argv)
  .scriptName('omniboard')
  .middleware(loggerMiddleware)
  .middleware(apiMiddleware)
  .demandCommand(1, 'Please provide at least one of the supported commands...')
  .command(analyzeCommand)
  .command(testConnectionCommand)
  .option('verbose', {
    type: 'boolean',
    default: false,
    description: 'Display debug level logs'
  })
  .option('api-key', {
    alias: 'ak',
    describe: 'API key generated by Omniboard app'
  })
  .alias('v', 'version')
  .alias('h', 'help')
  .epilogue(
    'for more information, find check out at https://omniboard.dev/docs'
  ).argv;
