import { Argv } from 'yargs';

import { ping } from '../services/api.service';
import { createLogger } from '../services/logger.service';

const logger = createLogger('TEST CONNECTION');

export const command = 'test-connection';

export const aliases = ['tc'];

export const describe = 'Test connection to Omniboard with provided API key';

export const builder = (yargs: Argv) =>
  yargs
    .option('--api-key', {
      alias: 'ak',
      describe: 'API key generated by Omniboard app'
    })
    .example('omniboard tc --api-key MY_API_KEY', '');

export const handler = async (argv: any) => {
  try {
    const { organization } = await ping();
    logger.success('connection successful, organization:', organization);
  } catch (err) {
    logger.error('connection failed, details:', err?.message);
    process.exit(1);
  }
};
